name: Deploy Home Assistant Integration
run-name: ${{ gitea.actor }} is deploying vmc_helty_flow integration 🚀
on: [push]

jobs:
  deploy-vmc-helty-flow-integration:
    runs-on: ubuntu-latest:docker://node:20-bullseye

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_FILE}" > $HOME/.kube/config
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

      - name: Get Home Assistant pod name
        id: getpod
        run: |
          POD_NAME=$(kubectl get pod -n home-assistant \
            -l app.kubernetes.io/name=home-assistant \
            -o jsonpath="{.items[0].metadata.name}")
          echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV

      - name: Copy integration to Home Assistant
        run: |
          kubectl cp components/vmc_helty_flow \
            $POD_NAME:/config/custom_components/ -n home-assistant

      - name: Rollout restart Home Assistant
        run: |
          kubectl rollout restart deployment -n home-assistant home-assistant

      - name: Wait for Home Assistant to become ready
        run: |
          kubectl rollout status deployment -n home-assistant home-assistant \
            --timeout=120s
