name: Deploy Home Assistant Integration
run-name: ${{ gitea.actor }} is deploying vmc_helty_flow integration  🚀

on:
  push

jobs:
  deploy-vmc-helty-flow-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Clean working directory
        run: |
          rm -rf /tmp/ha_vmc_helty_flow
      - name: Clone repository
        run: |
          echo "✅ Clono il branch ${{ gitea.ref_name }}"
          git clone --depth 1 --branch ${{ gitea.ref_name }} http://$GITEA_USER:$GITEA_TOKEN@gitea-service.git.svc.cluster.local:3000/dpezzoli/ha_vmc_helty_flow.git /tmp/ha_vmc_helty_flow
        env:
          GITEA_USER: dpezzoli
          GITEA_TOKEN: ${{ secrets.GITEATOKEN }}
      - name: Install kubectl (ARM64)
        run: |
          if command -v kubectl >/dev/null 2>&1; then
            echo "✅ kubectl già presente, salto l'installazione"
          else
            echo "⬇️ Scarico kubectl per ARM64"
            KUBE_VER=$(wget -qO- https://dl.k8s.io/release/stable.txt)
            wget -q "https://dl.k8s.io/release/${KUBE_VER}/bin/linux/arm64/kubectl" -O kubectl
            chmod +x kubectl
            mv kubectl /usr/local/bin/kubectl
          fi
      - name: Verify kubectl
        run: kubectl version --client=true --output=yaml
      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_FILE}" > $HOME/.kube/config
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

      - name: Get Home Assistant pod name
        id: getpod
        run: |
          POD_NAME=$(kubectl get pod -n home-assistant \
            -l app.kubernetes.io/name=home-assistant \
            -o jsonpath="{.items[0].metadata.name}")
          echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV

      - name: Copy integration to Home Assistant
        run: |
          kubectl cp /tmp/ha_vmc_helty_flow/custom_components/vmc_helty_flow/ \
            $POD_NAME:/config/custom_components/ -n home-assistant

      - name: Create www directory for Lovelace cards
        run: |
          kubectl exec $POD_NAME -n home-assistant -- \
            mkdir -p /config/www/vmc-helty-card

      - name: Copy VMC Helty Card to Home Assistant
        run: |
          kubectl cp /tmp/ha_vmc_helty_flow/www/vmc-helty-card/vmc-helty-card.js \
            $POD_NAME:/config/www/vmc-helty-card/ -n home-assistant
          kubectl cp /tmp/ha_vmc_helty_flow/www/vmc-helty-card/vmc-helty-card-editor.js \
            $POD_NAME:/config/www/vmc-helty-card/ -n home-assistant

      - name: Copy VMC Helty Card documentation
        run: |
          kubectl cp /tmp/ha_vmc_helty_flow/www/vmc-helty-card/README.md \
            $POD_NAME:/config/www/vmc-helty-card/ -n home-assistant
          kubectl cp /tmp/ha_vmc_helty_flow/www/vmc-helty-card/QUICK-START.md \
            $POD_NAME:/config/www/vmc-helty-card/ -n home-assistant
          kubectl cp /tmp/ha_vmc_helty_flow/www/vmc-helty-card/examples.md \
            $POD_NAME:/config/www/vmc-helty-card/ -n home-assistant

      - name: Add Lovelace resource configuration
        run: |
          kubectl exec $POD_NAME -n home-assistant -- bash -c '
            LOVELACE_CONFIG="/config/ui-lovelace.yaml"
            RESOURCE_URL="/local/vmc-helty-card/vmc-helty-card.js"

            # Create ui-lovelace.yaml if it does not exist
            if [ ! -f "$LOVELACE_CONFIG" ]; then
              echo "📝 Creating new ui-lovelace.yaml"
              echo "resources:" > "$LOVELACE_CONFIG"
              echo "  - url: /local/vmc-helty-card/vmc-helty-card.js" >> "$LOVELACE_CONFIG"
              echo "    type: module" >> "$LOVELACE_CONFIG"
              echo "" >> "$LOVELACE_CONFIG"
              echo "title: Home Assistant" >> "$LOVELACE_CONFIG"
              echo "views:" >> "$LOVELACE_CONFIG"
              echo "  - title: Home" >> "$LOVELACE_CONFIG"
              echo "    cards: []" >> "$LOVELACE_CONFIG"
            else
              # Check if resource already exists
              if ! grep -q "$RESOURCE_URL" "$LOVELACE_CONFIG"; then
                echo "➕ Adding VMC Helty Card resource to existing configuration"
                # Create backup
                cp "$LOVELACE_CONFIG" "$LOVELACE_CONFIG.backup.$(date +%Y%m%d_%H%M%S)"

                # Check if resources section exists
                if grep -q "^resources:" "$LOVELACE_CONFIG"; then
                  # Add to existing resources section
                  sed -i "/^resources:/a\\  - url: $RESOURCE_URL\\n    type: module" "$LOVELACE_CONFIG"
                else
                  # Add new resources section at the beginning
                  {
                    echo "resources:"
                    echo "  - url: $RESOURCE_URL"
                    echo "    type: module"
                    echo ""
                    cat "$LOVELACE_CONFIG"
                  } > "$LOVELACE_CONFIG.tmp" && mv "$LOVELACE_CONFIG.tmp" "$LOVELACE_CONFIG"
                fi
              else
                echo "✅ VMC Helty Card resource already configured"
              fi
            fi
          '

      - name: Verify VMC Helty Card installation
        run: |
          kubectl exec $POD_NAME -n home-assistant -- sh -c '
            echo "🔍 Verifying VMC Helty Card installation..."

            # Check files exist
            if [ -f "/config/www/vmc-helty-card/vmc-helty-card.js" ]; then
              echo "✅ vmc-helty-card.js installed"
              FILE_SIZE=$(wc -c < /config/www/vmc-helty-card/vmc-helty-card.js)
              echo "📊 File size: $FILE_SIZE bytes"
            else
              echo "❌ vmc-helty-card.js missing"
              exit 1
            fi

            if [ -f "/config/www/vmc-helty-card/vmc-helty-card-editor.js" ]; then
              echo "✅ vmc-helty-card-editor.js installed"
              FILE_SIZE=$(wc -c < /config/www/vmc-helty-card/vmc-helty-card-editor.js)
              echo "📊 File size: $FILE_SIZE bytes"
            else
              echo "❌ vmc-helty-card-editor.js missing"
              exit 1
            fi

            # Check Lovelace configuration
            if grep -q "/local/vmc-helty-card/vmc-helty-card.js" /config/ui-lovelace.yaml; then
              echo "✅ Lovelace resource configured"
            else
              echo "⚠️ Lovelace resource not found in configuration"
            fi

            echo "🎉 VMC Helty Card installation verified successfully!"
          '

      - name: Rollout restart Home Assistant
        run: |
          kubectl rollout restart deployment -n home-assistant home-assistant

      - name: Wait for Home Assistant to become ready
        run: |
          kubectl rollout status deployment -n home-assistant home-assistant \
            --timeout=120s
