blueprint:
  name: 🔥 Statistiche Riscaldamento Giornaliero per Stanza
  description: |
    Calcola e registra le ore giornaliere di funzionamento del termosifone di una stanza
    in base al target temperatura (> soglia). Salva i dati in un contatore e resetta a mezzanotte.
  domain: automation
  input:
    target_input:
      name: Helper Target Temperatura
      description: L'input_number che rappresenta la temperatura target della stanza.
      selector:
        entity:
          domain: input_number
    counter_input:
      name: Helper Contatore Ore
      description: L'input_number dove salvare le ore totali di riscaldamento giornaliere.
      selector:
        entity:
          domain: input_number
    start_time_input:
      name: Helper Start Time
      description: Input_text dove viene memorizzato l’orario di accensione.
      selector:
        entity:
          domain: input_text
    off_threshold:
      name: Soglia OFF
      description: Temperatura considerata come "spento".
      default: 5
      selector:
        number:
          min: 0
          max: 15
          unit_of_measurement: "°C"
          step: 0.5

trigger:
  - platform: state
    entity_id: !input target_input
    id: target_changed
  - platform: time
    at: "00:00:00"
    id: midnight

variables:
  soglia: !input off_threshold
  target_entity: !input target_input
  counter_entity: !input counter_input
  start_entity: !input start_time_input
  current_value: "{{ states(target_entity) | float(0) }}"
  previous_value: "{{ trigger.from_state.state | float(0) if trigger.from_state else 0 }}"
  accensione: "{{ (previous_value <= soglia) and (current_value > soglia) }}"
  spegnimento: "{{ (previous_value > soglia) and (current_value <= soglia) }}"

action:
  - choose:
      # --- Accensione ---
      - conditions:
          - condition: trigger
            id: target_changed
          - condition: template
            value_template: "{{ accensione }}"
        sequence:
          - service: input_text.set_value
            data:
              entity_id: "{{ start_entity }}"
              value: "{{ now() }}"
          - service: logbook.log
            data:
              name: "Riscaldamento {{ target_entity }}"
              message: "Acceso alle {{ now().strftime('%H:%M') }}"
              entity_id: "{{ target_entity }}"

      # --- Spegnimento ---
      - conditions:
          - condition: trigger
            id: target_changed
          - condition: template
            value_template: "{{ spegnimento }}"
        sequence:
          - variables:
              start_str: "{{ states(start_entity) }}"
              start_time: "{{ as_datetime(start_str, default=now()) }}"
              delta: "{{ (as_timestamp(now()) - as_timestamp(start_time)) / 3600 }}"
              current_hours: "{{ states(counter_entity) | float(0) }}"
              total_hours: "{{ (current_hours + delta) | round(2) }}"
          - service: input_number.set_value
            data:
              entity_id: "{{ counter_entity }}"
              value: "{{ total_hours }}"
          - service: input_text.set_value
            data:
              entity_id: "{{ start_entity }}"
              value: ""
          - service: logbook.log
            data:
              name: "Riscaldamento {{ target_entity }}"
              message: "Spento alle {{ now().strftime('%H:%M') }} (+{{ delta | round(2) }} ore)"
              entity_id: "{{ target_entity }}"

      # --- Reset giornaliero ---
      - conditions:
          - condition: trigger
            id: midnight
        sequence:
          - variables:
              today_hours: "{{ states(counter_entity) | float(0) }}"
          - service: logbook.log
            data:
              name: "Riscaldamento {{ target_entity }}"
              message: "Totale di oggi: {{ today_hours }} ore"
              entity_id: "{{ target_entity }}"
          - service: input_number.set_value
            data:
              entity_id: "{{ counter_entity }}"
              value: 0

mode: restart
