blueprint:
  name: 🔥 Statistiche Riscaldamento Giornaliero per Valvola
  description: |
    Calcola e registra le ore giornaliere di funzionamento del termosifone
    monitorando la temperatura impostata sulla valvola climate.
  domain: automation

  input:
    climate_entity:
      name: Valvola Termostatica
      description: L'entità climate da monitorare.
      selector:
        entity:
          domain: climate

    counter_input:
      name: Helper Contatore Ore
      description: L'input_number dove salvare le ore totali di riscaldamento giornaliere.
      selector:
        entity:
          domain: input_number

    start_time_input:
      name: Helper Start Time
      description: Input_text dove viene memorizzato l’orario di accensione.
      selector:
        entity:
          domain: input_text

    off_threshold:
      name: Soglia OFF
      description: Temperatura considerata come "spento".
      default: 5
      selector:
        number:
          min: 0
          max: 15
          step: 0.5
          unit_of_measurement: "°C"

trigger:
  - platform: state
    entity_id: !input climate_entity
    attribute: temperature
    id: temperature_changed
  - platform: time
    at: "00:00:00"
    id: midnight

variables:
  soglia: !input off_threshold
  climate: !input climate_entity
  counter_entity: !input counter_input
  start_entity: !input start_time_input
  current_value: "{{ state_attr(climate, 'temperature') | float(0) }}"
  previous_value: "{{ trigger.from_state.attributes.temperature | float(0) if trigger.from_state else 0 }}"
  accensione: "{{ (previous_value <= soglia) and (current_value > soglia) }}"
  spegnimento: "{{ (previous_value > soglia) and (current_value <= soglia) }}"

action:
  - choose:
      # --- Accensione ---
      - conditions:
          - condition: trigger
            id: temperature_changed
          - condition: template
            value_template: "{{ accensione }}"
        sequence:
          - service: input_text.set_value
            data:
              entity_id: "{{ start_entity }}"
              value: "{{ now() }}"
          - service: logbook.log
            data:
              name: "Riscaldamento {{ climate }}"
              message: "Acceso alle {{ now().strftime('%H:%M') }}"
              entity_id: "{{ climate }}"

      # --- Spegnimento ---
      - conditions:
          - condition: trigger
            id: temperature_changed
          - condition: template
            value_template: "{{ spegnimento }}"
        sequence:
          - variables:
              start_str: "{{ states(start_entity) }}"
              start_time: "{{ as_datetime(start_str, default=now()) }}"
              delta: "{{ (as_timestamp(now()) - as_timestamp(start_time)) / 3600 }}"
              current_hours: "{{ states(counter_entity) | float(0) }}"
              total_hours: "{{ (current_hours + delta) | round(2) }}"
          - service: input_number.set_value
            data:
              entity_id: "{{ counter_entity }}"
              value: "{{ total_hours }}"
          - service: input_text.set_value
            data:
              entity_id: "{{ start_entity }}"
              value: ""
          - service: logbook.log
            data:
              name: "Riscaldamento {{ climate }}"
              message: "Spento alle {{ now().strftime('%H:%M') }} (+{{ delta | round(2) }} ore)"
              entity_id: "{{ climate }}"

      # --- Reset giornaliero ---
      - conditions:
          - condition: trigger
            id: midnight
        sequence:
          - variables:
              today_hours: "{{ states(counter_entity) | float(0) }}"
          - service: logbook.log
            data:
              name: "Riscaldamento {{ climate }}"
              message: "Totale di oggi: {{ today_hours }} ore"
              entity_id: "{{ climate }}"
          - service: input_number.set_value
            data:
              entity_id: "{{ counter_entity }}"
              value: 0

mode: restart
