blueprint:
  name: VMC Helty Flow - Cicli Boost Giorno/Notte
  description: >
    Gestisce cicli boost/day-night della VMC Helty Flow.
    - Stato boost persistente tramite input_boolean
    - Intervalli e durata configurabili separatamente per giorno/notte
    - Trigger ogni 5 minuti
    - Velocità fan 0/25/50/75/100%
    - Pausa opzionale tramite input_boolean
    - Spegnimento automatico del boost quando scade la durata
  domain: automation

  input:
    vmc_entity:
      name: Entità VMC (fan)
      selector:
        entity:
          domain: fan

    boost_state:
      name: Helper stato boost (input_boolean)
      description: "Indica se attualmente siamo in boost (persistente)"
      selector:
        entity:
          domain: input_boolean

    pause_switch:
      name: Pausa automazione (input_boolean opzionale)
      description: "Se ON, blocca cicli boost"
      default: ""
      selector:
        entity:
          domain: input_boolean

    day_start:
      name: Inizio Giorno
      default: "08:00:00"
      selector:
        time: {}

    night_start:
      name: Inizio Notte
      default: "23:00:00"
      selector:
        time: {}

    day_boost_interval:
      name: Intervallo Boost Giorno (minuti)
      default: 30
      selector:
        number:
          min: 5
          max: 1440
          step: 5
          unit_of_measurement: minutes

    day_boost_duration:
      name: Durata Boost Giorno (minuti)
      default: 10
      selector:
        number:
          min: 5
          max: 180
          step: 5
          unit_of_measurement: minutes

    night_boost_interval:
      name: Intervallo Boost Notte (minuti)
      default: 60
      selector:
        number:
          min: 5
          max: 1440
          step: 5
          unit_of_measurement: minutes

    night_boost_duration:
      name: Durata Boost Notte (minuti)
      default: 10
      selector:
        number:
          min: 5
          max: 180
          step: 5
          unit_of_measurement: minutes

    day_base_fan:
      name: Velocità base giorno
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 25

    day_boost_fan:
      name: Velocità boost giorno
      default: 75
      selector:
        number:
          min: 0
          max: 100
          step: 25

    night_base_fan:
      name: Velocità base notte
      default: 25
      selector:
        number:
          min: 0
          max: 100
          step: 25

    night_boost_fan:
      name: Velocità boost notte
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 25

mode: restart
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: "/5"

variables:
  vmc_entity: !input vmc_entity
  boost_state: !input boost_state
  pause_switch: !input pause_switch
  day_start: !input day_start
  night_start: !input night_start
  day_boost_interval: !input day_boost_interval
  day_boost_duration: !input day_boost_duration
  night_boost_interval: !input night_boost_interval
  night_boost_duration: !input night_boost_duration
  day_base_fan: !input day_base_fan
  day_boost_fan: !input day_boost_fan
  night_base_fan: !input night_base_fan
  night_boost_fan: !input night_boost_fan

action:
  - variables:
      now_time: "{{ now().time() }}"
      timestamp_str: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      day_start_time: "{{ strptime(day_start, '%H:%M:%S').time() }}"
      night_start_time: "{{ strptime(night_start, '%H:%M:%S').time() }}"
      is_day: "{{ day_start_time <= now_time < night_start_time }}"

      cur_interval_min: "{{ day_boost_interval if is_day else night_boost_interval }}"
      cur_duration_min: "{{ day_boost_duration if is_day else night_boost_duration }}"
      cur_boost_pct: "{{ day_boost_fan if is_day else night_boost_fan }}"
      cur_base_pct: "{{ day_base_fan if is_day else night_base_fan }}"
      period_label: "{{ 'giorno' if is_day else 'notte' }}"

      last_boost_ts: >
        {% set obj = states[boost_state] %}
        {{ as_timestamp(obj.last_changed) }}

      seconds_since_last_boost: >
        {% if last_boost_ts|int > 0 %}
          {{ (as_timestamp(now()) - last_boost_ts) | int }}
        {% else %}
          999999
        {% endif %}

      in_boost: "{{ is_state(boost_state,'on') }}"
      ready_for_boost: "{{ not in_boost and seconds_since_last_boost >= (cur_interval_min|int)*60 }}"
      in_boost_expired: >
        {% if in_boost %}
          {{ seconds_since_last_boost >= (cur_duration_min|int)*60 }}
        {% else %}
          false
        {% endif %}

  # Pausa attiva → skip
  - condition: template
    value_template: >
      {% if pause_switch != '' %}
        {{ is_state(pause_switch,'off') }}
      {% else %}
        true
      {% endif %}

  # Log debug
  - service: logbook.log
    data:
      name: "VMC Helty"
      message: >
        [{{ timestamp_str }}] Debug {{ period_label }}:
        in_boost={{ in_boost }}, in_boost_expired={{ in_boost_expired }},
        ready_for_boost={{ ready_for_boost }},
        last_boost_ts={{ last_boost_ts }},
        now_less_last_boot={{ (as_timestamp(now()) - last_boost_ts) | int }},
        seconds_since_last_boost={{ seconds_since_last_boost }},
        
        fan_pct={{ state_attr(vmc_entity,'percentage') }}%

  # 1) Se in boost ma è scaduto -> spegni boost e ripristina base
  - condition: template
    value_template: "{{ in_boost_expired }}"
  - service: input_boolean.turn_off
    target:
      entity_id: "{{ boost_state }}"
  - service: fan.set_percentage
    target:
      entity_id: "{{ vmc_entity }}"
    data:
      percentage: "{{ cur_base_pct }}"
  - service: logbook.log
    data:
      name: "VMC Helty"
      message: >
        [{{ timestamp_str }}] ⏹️ Boost scaduto ({{ period_label }}) - durata {{ cur_duration_min }} min.
        Ripristino velocità base {{ cur_base_pct }}%.

  # 2) Se pronto per nuovo boost -> attiva boost (setta helper ON) e imposta boost
  - condition: template
    value_template: "{{ ready_for_boost }}"
  - service: input_boolean.turn_on
    target:
      entity_id: "{{ boost_state }}"
  - service: fan.set_percentage
    target:
      entity_id: "{{ vmc_entity }}"
    data:
      percentage: "{{ cur_boost_pct }}"
  - service: logbook.log
    data:
      name: "VMC Helty"
      message: >
        [{{ timestamp_str }}] 🚀 Avvio nuovo boost ({{ period_label }}) → {{ cur_boost_pct }} %
        (durata={{ cur_duration_min }} min; intervallo={{ cur_interval_min }} min)

  # 3) Se già in boost e non scaduto -> mantieni boost
  - condition: template
    value_template: "{{ in_boost and not in_boost_expired }}"
  - service: fan.set_percentage
    target:
      entity_id: "{{ vmc_entity }}"
    data:
      percentage: "{{ cur_boost_pct }}"
  - service: logbook.log
    data:
      name: "VMC Helty"
      message: >
        [{{ timestamp_str }}] 🔄 Boost in corso ({{ period_label }}) → mantiene {{ cur_boost_pct }} %

  # 4) Default -> non in boost e non pronto -> assicurati base e helper OFF
  - condition: template
    value_template: "{{ not in_boost and not ready_for_boost }}"
  - service: fan.set_percentage
    target:
      entity_id: "{{ vmc_entity }}"
    data:
      percentage: "{{ cur_base_pct }}"
  - service: input_boolean.turn_off
    target:
      entity_id: "{{ boost_state }}"
  - service: logbook.log
    data:
      name: "VMC Helty"
      message: >
        [{{ timestamp_str }}] ✅ Ventola a velocità base ({{ period_label }}) → {{ cur_base_pct }} %
