blueprint:
  name: VMC Helty Flow - Cicli Boost Giorno/Notte
  description: >
    Gestisce automaticamente la velocità della ventola della VMC Helty Flow
    con cicli di boost e velocità base differenziati tra giorno e notte.
  domain: automation
  input:
    vmc_entity:
      name: Entità VMC
      description: Entità del ventilatore VMC Helty (es. fan.vmc_helty_soggiorno)
      selector:
        entity:
          domain: fan

    day_start:
      name: Inizio Giorno
      description: Ora di inizio del periodo diurno
      default: "08:00:00"
      selector:
        time: {}

    night_start:
      name: Inizio Notte
      description: Ora di inizio del periodo notturno
      default: "23:00:00"
      selector:
        time: {}

    day_boost_interval:
      name: Intervallo Boost Giorno (minuti)
      default: 30
      selector:
        number:
          min: 5
          max: 240
          unit_of_measurement: "min"
          mode: box

    day_boost_duration:
      name: Durata Boost Giorno (minuti)
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "min"
          mode: box

    night_boost_interval:
      name: Intervallo Boost Notte (minuti)
      default: 60
      selector:
        number:
          min: 5
          max: 240
          unit_of_measurement: "min"
          mode: box

    night_boost_duration:
      name: Durata Boost Notte (minuti)
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "min"
          mode: box

    day_base_fan:
      name: Velocità base giorno
      description: Percentuale (0=spento, 25=bassa, 50=media, 75=alta, 100=max)
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 25
          unit_of_measurement: "%"

    day_boost_fan:
      name: Velocità boost giorno
      description: Percentuale (0=spento, 25=bassa, 50=media, 75=alta, 100=max)
      default: 75
      selector:
        number:
          min: 0
          max: 100
          step: 25
          unit_of_measurement: "%"

    night_base_fan:
      name: Velocità base notte
      description: Percentuale (0=spento, 25=bassa, 50=media, 75=alta, 100=max)
      default: 25
      selector:
        number:
          min: 0
          max: 100
          step: 25
          unit_of_measurement: "%"

    night_boost_fan:
      name: Velocità boost notte
      description: Percentuale (0=spento, 25=bassa, 50=media, 75=alta, 100=max)
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 25
          unit_of_measurement: "%"

mode: restart
max_exceeded: silent

variables:
  vmc_entity: !input vmc_entity
  day_start: !input day_start
  night_start: !input night_start
  day_boost_interval: !input day_boost_interval
  day_boost_duration: !input day_boost_duration
  night_boost_interval: !input night_boost_interval
  night_boost_duration: !input night_boost_duration
  day_base_fan: !input day_base_fan
  day_boost_fan: !input day_boost_fan
  night_base_fan: !input night_base_fan
  night_boost_fan: !input night_boost_fan

trigger:
  - platform: time_pattern
    minutes: "/1"

action:
  - variables:
      now_time: "{{ now().time() }}"
      day_start_time: "{{ strptime(day_start, '%H:%M:%S').time() }}"
      night_start_time: "{{ strptime(night_start, '%H:%M:%S').time() }}"
      is_day: >
        {{ day_start_time <= now_time < night_start_time }}

  - choose:
      - conditions: "{{ is_day }}"
        sequence:
          - service: fan.set_percentage
            target:
              entity_id: "{{ vmc_entity }}"
            data:
              percentage: "{{ day_base_fan }}"
          - delay:
              minutes: "{{ day_boost_interval }}"
          - service: fan.set_percentage
            target:
              entity_id: "{{ vmc_entity }}"
            data:
              percentage: "{{ day_boost_fan }}"
          - delay:
              minutes: "{{ day_boost_duration }}"
      - conditions: "{{ not is_day }}"
        sequence:
          - service: fan.set_percentage
            target:
              entity_id: "{{ vmc_entity }}"
            data:
              percentage: "{{ night_base_fan }}"
          - delay:
              minutes: "{{ night_boost_interval }}"
          - service: fan.set_percentage
            target:
              entity_id: "{{ vmc_entity }}"
            data:
              percentage: "{{ night_boost_fan }}"
          - delay:
              minutes: "{{ night_boost_duration }}"
