blueprint:
  name: VMC Helty Flow - Cicli Boost Giorno/Notte
  description: >
    Gestisce automaticamente la velocità della ventola della VMC Helty Flow
    con cicli boost e base separati per giorno e notte, intervallo e durata boost configurabili.
  domain: automation
  input:
    vmc_entity:
      name: Entità VMC
      description: L'entità fan.* della VMC
      selector:
        entity:
          domain: fan

    day_start:
      name: Ora inizio giorno
      default: "08:00:00"
      selector:
        time: {}

    night_start:
      name: Ora inizio notte
      default: "22:00:00"
      selector:
        time: {}

    day_base_fan:
      name: Velocità base giorno
      default: "50"
      selector:
        select:
          options:
            - label: Low (25%)
              value: "25"
            - label: Medium (50%)
              value: "50"
            - label: High (75%)
              value: "75"
            - label: Max (100%)
              value: "100"

    day_boost_fan:
      name: Velocità boost giorno
      default: "75"
      selector:
        select:
          options:
            - label: Low (25%)
              value: "25"
            - label: Medium (50%)
              value: "50"
            - label: High (75%)
              value: "75"
            - label: Max (100%)
              value: "100"

    night_base_fan:
      name: Velocità base notte
      default: "25"
      selector:
        select:
          options:
            - label: Low (25%)
              value: "25"
            - label: Medium (50%)
              value: "50"
            - label: High (75%)
              value: "75"
            - label: Max (100%)
              value: "100"

    night_boost_fan:
      name: Velocità boost notte
      default: "50"
      selector:
        select:
          options:
            - label: Low (25%)
              value: "25"
            - label: Medium (50%)
              value: "50"
            - label: High (75%)
              value: "75"
            - label: Max (100%)
              value: "100"

    day_boost_interval:
      name: Intervallo boost giorno (minuti)
      default: 60
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: "min"

    day_boost_duration:
      name: Durata boost giorno (minuti)
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "min"

    night_boost_interval:
      name: Intervallo boost notte (minuti)
      default: 120
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: "min"

    night_boost_duration:
      name: Durata boost notte (minuti)
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "min"

mode: restart

trigger:
  - platform: time_pattern
    minutes: "*"  # Controllo ogni minuto

variables:
  now_time: "{{ now().time() }}"
  is_day: >
    {{ now_time >= strptime(day_start, '%H:%M:%S').time() and
       now_time < strptime(night_start, '%H:%M:%S').time() }}

  interval: "{{ day_boost_interval if is_day else night_boost_interval }}"
  duration: "{{ day_boost_duration if is_day else night_boost_duration }}"
  boost_level: "{{ day_boost_fan if is_day else night_boost_fan }}"
  base_level: "{{ day_base_fan if is_day else night_base_fan }}"

condition:
  - condition: template
    value_template: >
      {% set last = state_attr('automation.' ~ automation.entity_id.split('.')[1], 'last_triggered') %}
      {% if last is none %}
        true
      {% else %}
        {{ (now() - last).total_seconds() / 60 >= interval }}
      {% endif %}

action:
  - service: fan.set_percentage
    target:
      entity_id: !input vmc_entity
    data:
      percentage: "{{ boost_level }}"
  - delay:
      minutes: "{{ duration }}"
  - service: fan.set_percentage
    target:
      entity_id: !input vmc_entity
    data:
      percentage: "{{ base_level }}"
