blueprint:
  name: VMC Helty Flow - Cicli Boost Giorno/Notte
  description: >
    Gestisce automaticamente la velocità della ventola della VMC Helty Flow
    con cicli boost e base separati per giorno e notte, intervallo e durata boost configurabili.
  domain: automation
  input:
    vmc_entity:
      name: Entità  VMC
      description: L'entità  fan.* della VMC
      selector:
        entity:
          domain: fan

    day_start:
      name: Ora inizio giorno
      default: "08:00:00"
      selector:
        time: {}

    night_start:
      name: Ora inizio notte
      default: "22:00:00"
      selector:
        time: {}

    day_base_fan:
      name: Velocità  base giorno
      description: Valore ventola quando è giorno (base)
      default: "50"
      selector:
        select:
          options:
            - label: Low (25%)
              value: "25"
            - label: Medium (50%)
              value: "50"
            - label: High (75%)
              value: "75"
            - label: Max (100%)
              value: "100"

    day_boost_fan:
      name: Velocità  boost giorno
      description: Valore ventola quando è giorno (boost)
      default: "75"
      selector:
        select:
          options:
            - label: Low (25%)
              value: "25"
            - label: Medium (50%)
              value: "50"
            - label: High (75%)
              value: "75"
            - label: Max (100%)
              value: "100"

    night_base_fan:
      name: Velocità  base notte
      description: Valore ventola quando è notte (base)
      default: "25"
      selector:
        select:
          options:
            - label: Low (25%)
              value: "25"
            - label: Medium (50%)
              value: "50"
            - label: High (75%)
              value: "75"
            - label: Max (100%)
              value: "100"

    night_boost_fan:
      name: Velocità  boost notte
      description: Valore ventola quando è notte (boost)
      default: "50"
      selector:
        select:
          options:
            - label: Low (25%)
              value: "25"
            - label: Medium (50%)
              value: "50"
            - label: High (75%)
              value: "75"
            - label: Max (100%)
              value: "100"

    boost_interval:
      name: Intervallo tra boost (minuti)
      description: Ogni quanti minuti attivare il boost
      default: 60
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: "min"

    boost_duration:
      name: Durata boost (minuti)
      description: Per quanti minuti il boost resta attivo
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "min"

mode: restart

trigger:
  - platform: time_pattern
    minutes: "/!input boost_interval"

action:
  - choose:
      - conditions:
          - condition: time
            after: !input day_start
            before: !input night_start
        sequence:
          - service: fan.set_percentage
            target:
              entity_id: !input vmc_entity
            data:
              percentage: !input day_boost_fan
          - delay:
              minutes: !input boost_duration
          - service: fan.set_percentage
            target:
              entity_id: !input vmc_entity
            data:
              percentage: !input day_base_fan
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: !input night_start
              - condition: time
                before: !input day_start
        sequence:
          - service: fan.set_percentage
            target:
              entity_id: !input vmc_entity
            data:
              percentage: !input night_boost_fan
          - delay:
              minutes: !input boost_duration
          - service: fan.set_percentage
            target:
              entity_id: !input vmc_entity
            data:
              percentage: !input night_base_fan
